### ISSUE TITLE
Triage milestones for all issues

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2073]
We need to triage all of our issues to make sure we know exactly which ones are required for 1.0.
Editors' plan to break this up into (ordered) steps:

1. In [the post-V1 milestone](https://github.com/gpuweb/gpuweb/milestones/post-V1) (formerly known as "post-MVP"):
    - [ ] Ensure everything is actually post-V1. (currently 39 to review)
2. In [the project with filter `is:open no:milestone`](https://github.com/orgs/gpuweb/projects/1?card_filter_query=is%3Aopen+no%3Amilestone):
    - [ ] Set milestones on everything under "Needs Investigation/Proposal or Revision". (currently 21)
    - [ ] Set milestones on everything under "Needs Specification". (currently 38)
3. And finally for everything else:
    - [ ] Set milestones on every remaining issue in [`is:issue is:open no:milestone`](https://github.com/gpuweb/gpuweb/issues?q=is%3Aissue+is%3Aopen+no%3Amilestone) (currently 306, should have gone down a little bit by the time we reach this step)
    - [ ] Set milestones on every remaining PR in [`is:pr is:open no:milestone`](https://github.com/gpuweb/gpuweb/pulls?q=is%3Apr+is%3Aopen+no%3Amilestone) (currently 30)

**Comment by Kangz** [comment]
I gave a first shot at triaging all API issues. Sorry all for the spam!

This is the list of [issues I closed](https://github.com/gpuweb/gpuweb/issues?q=closed%3A2021-09-02+is%3Aclosed) if you want to check for false positives.

**Comment by jdashg** [comment]
FYI on Tuesday we found disagreement on the consensus regarding MVP vs OT vs V1 that was reached in the Monday meeting.
We really need to talk about that more, so probably ease up on the changes for now.

**Comment by Kangz** [comment]
Closing this since we triaged all issues for v1.
