### ISSUE TITLE
Seek horizontal reviews

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2531]
This is a meta issue to track horizontal review steps for the specification.
See [How to do wide review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) for details.

- Accessibility
    - [x] Work through <a rel="nofollow" class="external text" href="https://w3c.github.io/apa/fast/checklist.html">this questionnaire</a>
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/a11y-request/issues/new/choose">request a review via GitHub</a> from <a rel="nofollow" class="external text" href="https://www.w3.org/WAI/APA/">APA</a>
      - APA already reviewed [WebGPU](https://www.w3.org/WAI/APA/wiki/WebGPU) and [WGSL](https://www.w3.org/WAI/APA/wiki/WebGPU_Shading_Language)
- Architecture
    - [x] Ask the <a rel="nofollow" class="external text" href="https://www.w3.org/2001/tag/">TAG</a> for review; see <a rel="nofollow" class="external text" href="https://tag.w3.org/workmode/">how to work with the TAG</a>
      - https://github.com/w3ctag/design-reviews/issues/626
    - [ ] If you are developing javascript APIs you may also want to ask <a rel="nofollow" class="external text" href="mailto:public-script-coord@w3.org">public-script-coord@w3.org</a>, a technical discussion list shared by W3C and ECMA's TC 39
- Internationalisation
    - [x] Read the <a rel="nofollow" class="external text" href="https://www.w3.org/International/review-request">Request a review</a> page
    - [x] work through the <a rel="nofollow" class="external text" href="https://w3c.github.io/i18n-drafts/techniques/shortchecklist">Short Checklist</a>
      - https://github.com/gpuweb/gpuweb/issues/2546
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/i18n-request/issues/new/choose">request a review via GitHub</a>
      - https://github.com/w3c/i18n-request/issues/174
- Privacy
    - [x] Write a "Privacy Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://w3ctag.github.io/security-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>, <a rel="nofollow" class="external text" href="https://w3c.github.io/fingerprinting-guidance/">Mitigating Browser Fingerprinting in Web Specifications</a>, and <a rel="nofollow" class="external text" href="https://tools.ietf.org/html/rfc6973">RFC6973</a>
    - [X] <a rel="nofollow" class="external text" href="https://github.com/w3cping/privacy-request/issues/new/choose">request a review via GitHub</a> from the <a rel="nofollow" class="external text" href="https://www.w3.org/Privacy/">Privacy Interest Group</a>
      - https://github.com/w3cping/privacy-request/issues/85
- Security
    - [x] Write a "Security Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://w3ctag.github.io/security-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>
      - The [security and privacy questionnaire](https://gpuweb.github.io/gpuweb/explainer/#questionnaire) is part of the larger WebGPU explainer.
    - [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/security-request/issues/new/choose">request a review via GitHub</a>
       - https://github.com/w3c/security-request/issues/23
