### ISSUE TITLE
Tracking issue for Bikeshed issues for the spec.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2709]
- [ ] https://github.com/tabatkins/bikeshed/issues/1740
   - [ ] https://github.com/plinss/widlparser/issues/56

**Comment by kainino0x** [comment]
- [ ] https://github.com/tabatkins/bikeshed/pull/1744
- [ ] Cross linking between WebGPU and WGSL https://github.com/tabatkins/bikeshed/issues/2006

**Comment by kainino0x** [comment]
- [ ] Can't use Bikeshed API (`make online`) if we specs into multiple files (No issue filed?)
    - https://github.com/gpuweb/gpuweb/pull/833#issuecomment-640792219

**Comment by kainino0x** [comment]
- [ ] https://github.com/gpuweb/gpuweb/issues/3222

**Comment by kainino0x** [comment]
- [ ] https://github.com/plinss/widlparser/issues/79
  - Blocking https://github.com/gpuweb/gpuweb/issues/3709

**Comment by kainino0x** [comment]
- https://github.com/speced/bikeshed/issues/2476
